apiVersion: v1
kind: Service
metadata:
  name: nginx-ms
  namespace: nginx-ms
spec:
  selector:
    app: nginx-ms
  ports:
    - protocol: TCP
      name: rtmp
      port: 1935
      targetPort: 1935
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
